name: rogers_dictionary
description: The electronic version of Dr Rogers Spanish Medical Dictionary.

publish_to: 'none'

version: 1.1.0+25

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animations: ^2.0.0
  async: ^2.8.1
  async_list_view: ^1.0.0
  cupertino_icons: ^1.0.3
  device_info_plus: ^9.0.2
  email_validator: ^2.0.1
  feedback:
    path: ../feedback/feedback
  firebase_analytics: ^10.5.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0
  http: ^1.1.0
  implicit_navigator:
    path: ../implicit_navigator
  in_app_purchase: ^3.0.8
  just_audio: ^0.9.35
  notified_preferences: ^2.0.0
  package_info_plus: ^5.0.1
  path: ^1.8.0
  path_provider: ^2.0.1
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.13
  sqflite: ^2.0.0+3

dev_dependencies:
  firedart: ^0.9.0+1
  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.13.1
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.0.1+1
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  msix: ^3.7.0
  screenshot: ^2.1.0
  sqflite_common_ffi: ^2.0.0
  test: ^1.24.1
  device_frame:
    path: ../flutter_device_preview/device_frame
  image: ^4.0.17
  ml_dataframe: ^1.6.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/glenn.png
    - assets/

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_android: "assets/images/n_logo_flat.png"
  image_path_ios: "assets/images/n_logo_ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/n_logo_foreground.png"

flutter_native_splash:
  color: "ffffff"
  branding: "assets/images/n_logo_splash.png"
  android_gravity: top
  ios_content_mode: center

msix_config:
  display_name: Rogers Dictionary
  publisher_display_name: Rogers Dictionary
  identity_name: com.rogers.dictionary
  msix_version: 0.0.1.0
  certificate_path: C:\Users\Waffl\Documents\code\rogers_dictionary\keys\not_a_virus.pfx
  certificate_password: notavirus
  publisher: E=caseycrogers@berkeley.edu, CN=Rogers Dictionary, O=Rogers Dictionary, L=Willits, S=California, C=US
  architecture: x64
